name: Build and Deploy to QA 

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:      
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'sandbox'  


permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: ${{ github.event.inputs.environment || 'sandbox' }}
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (build)
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-central-1
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Load .env (optional)
      run: |
        if [ -n "${{ vars.ENV_FILE_URL }}" ]; then
          if [[ "${{ vars.ENV_FILE_URL }}" == s3://* ]]; then
            aws s3 cp "${{ vars.ENV_FILE_URL }}" .env
          else
            curl -fsSL "${{ vars.ENV_FILE_URL }}" -o .env
          fi
        fi
    - name: Install dependencies
      run: npm ci
    - name: Build static web (Vite)
      env:
        CI: ''
      run: npm run build
    - name: Store the build in s3
      run:  |
        aws s3 sync --delete ./dist s3://${{ vars.BUILD_BUCKET }}/shopify-dummy/build/${{ github.sha }}
        aws s3 sync --delete ./dist s3://${{ vars.BUILD_BUCKET }}/shopify-dummy/build/sandbox         
  deploy:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/heads/releases/')
    timeout-minutes: 20
    environment: ${{ github.event.inputs.environment || 'sandbox' }}
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (deploy)
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-central-1
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

    - name: Download the build
      env:
        CI: ''
      run: |
        mkdir build
        aws s3 sync s3://${{ vars.BUILD_BUCKET }}/shopify-dummy/build/${{ github.sha }} ./build

    - name: Deploy
      uses: reggionick/s3-deploy@v4
      with:
        folder: build
        bucket: ${{ vars.S3_BUCKET }}
        bucket-region: ${{ vars.S3_BUCKET_REGION }}
        dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
        files-to-include: '{.*/**,**}'